project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!guidance/SOP.md"

website:
  title: "SE D&A GitHub Guides"
  site-url: "https://nhsengland.github.io/se-da-github-guide/"
  sidebar:
    foreground: "black"
    # background: "#EBF5FF"
    background: "#005eb833"
    style: "docked"
    search: true
    contents:
      - pages/intro-to-github.qmd
      - section: "GitHub Guides"
        contents:
          - pages/first-repo.qmd
          - pages/github-desktop.qmd
          - pages/r-studio.qmd
          - pages/vs-code.qmd
          - pages/databricks-github.qmd
          - pages/fdp.qmd
      - section: "Principles"
        contents:
          - pages/understanding-code.qmd
          - pages/qasar.qmd
      - section: "Placeholder"
        contents:
          - pages/another-page.qmd

format:
  html:
    toc: true
    css: styles.css

execute:
  freeze: auto